module.exports = {
  apps: [
    {
      name: 'resto-nodeserver',
      cwd: './server',
      script: 'app.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 2000,
        // BRANCH_COMPARE_PUBLIC_URL and TELEGRAM_MINIAPP_SECRET come from .env (see .env.example).
        // Avoid inherited IDE/sandbox proxy breaking outbound HTTPS calls (Telegram, Google APIs).
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        ALL_PROXY: '',
        all_proxy: '',
        GIT_HTTP_PROXY: '',
        GIT_HTTPS_PROXY: '',
        SOCKS_PROXY: '',
        SOCKS5_PROXY: '',
        socks_proxy: '',
        socks5_proxy: '',
        NO_PROXY: '127.0.0.1,::1,localhost',
        no_proxy: '127.0.0.1,::1,localhost',
      },
    },
    {
      name: 'resto-frontend',
      cwd: '.',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
    },
    {
      name: 'resto-pyserver',
      cwd: './pyserver',
      script: './.venv/bin/python',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 2100 --no-access-log',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PYTHONUNBUFFERED: '1',
        PORT: 2100,
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        ALL_PROXY: '',
        all_proxy: '',
        GIT_HTTP_PROXY: '',
        GIT_HTTPS_PROXY: '',
        SOCKS_PROXY: '',
        SOCKS5_PROXY: '',
        socks_proxy: '',
        socks5_proxy: '',
        NO_PROXY: '127.0.0.1,::1,localhost',
        no_proxy: '127.0.0.1,::1,localhost',
      },
    },
  ],
};
